UPDATE medewerkers SET foto_key = CASE naam
  WHEN 'Teunis Sikma' THEN 'https://www.fresh-forward.nl/thumbnail/team/1074/foto-teunis.jpg'
  WHEN 'Bert Meulenbroek' THEN 'https://www.fresh-forward.nl/thumbnail/team/75/bert-1.jpg'
  WHEN 'Joanna Pabiniak' THEN 'https://www.fresh-forward.nl/thumbnail/team/1083/joanna-zw.jpg'
  WHEN 'Stephan Geerlings' THEN 'https://www.fresh-forward.nl/thumbnail/team/1073/foto-stephan.jpg'
  WHEN 'Peter-Jan van Ingen' THEN 'https://www.fresh-forward.nl/thumbnail/team/1054/pj-2024-zwart-wit.jpeg'
  WHEN 'Ingrid van der Bogt' THEN 'https://www.fresh-forward.nl/thumbnail/team/694/ingrid-van-der-bogt.jpg'
  WHEN 'Robert Hooftman' THEN 'https://www.fresh-forward.nl/thumbnail/team/1089/robert-hooftman-zw.jpg'
  WHEN 'Carina van der Lippe' THEN 'https://www.fresh-forward.nl/thumbnail/team/73/carina-1.jpg'
  WHEN 'Lucie Bartels' THEN 'https://www.fresh-forward.nl/thumbnail/team/695/lucie-bartels.jpg'
  WHEN 'Ilja Berendsen-van der Woude' THEN 'https://www.fresh-forward.nl/thumbnail/team/1075/whatsapp-image-2024-01-30-at-133036-zw-wit.jpeg'
  WHEN 'Nick Howard' THEN 'https://www.fresh-forward.nl/thumbnail/team/860/nick-howard-headshot-2.png'
  WHEN 'Evert Walraven' THEN 'https://www.fresh-forward.nl/thumbnail/team/858/evert-2.jpg'
  WHEN 'Anke Fischer' THEN 'https://www.fresh-forward.nl/thumbnail/team/1055/dsc3448-sw.jpg'
  WHEN 'Thijs van Dijk' THEN 'https://www.fresh-forward.nl/thumbnail/team/81/thijs-1.jpg'
  WHEN 'Rob d''Hont' THEN 'https://www.fresh-forward.nl/thumbnail/team/82/rob-dh-1.jpg'
  WHEN 'Gerwin Peters' THEN 'https://www.fresh-forward.nl/thumbnail/team/1056/whatsapp-image-2024-01-30-at-133040-zw-wit.jpeg'
  WHEN 'Yanning Wang' THEN 'https://www.fresh-forward.nl/thumbnail/team/1085/afbeelding-20260211-141521-2af10614.jpeg'
  WHEN 'Johan Willemsen' THEN 'https://www.fresh-forward.nl/thumbnail/team/690/johan-willemsen.jpg'
  WHEN 'Tim Koorevaar' THEN 'https://www.fresh-forward.nl/thumbnail/team/869/tim-2.jpg'
  WHEN 'Marina Gomez-Caro Gonzalez' THEN 'https://www.fresh-forward.nl/thumbnail/team/687/marina-gomez.jpg'
  WHEN 'Rian Zegers-Peters' THEN 'https://www.fresh-forward.nl/thumbnail/team/990/whatsapp-image-2022-11-01-at-34012-pm.jpeg'
  WHEN 'Ruud Venner' THEN 'https://www.fresh-forward.nl/thumbnail/team/692/ruud-venner-kopie-2.jpg'
  WHEN 'Jiahui Lin' THEN 'https://www.fresh-forward.nl/thumbnail/team/1064/foto-lin-zw-w.jpg'
  WHEN 'Saskia van Vulpen' THEN 'https://www.fresh-forward.nl/thumbnail/team/469/341.jpg'
  WHEN 'Wendelien de Graaf' THEN 'https://www.fresh-forward.nl/thumbnail/team/1060/wendelien-zwart-wit-gespiegeld.jpg'
  WHEN 'Imke van Asseldonk-van den Hoven' THEN 'https://www.fresh-forward.nl/thumbnail/team/1006/whatsapp-image-2023-05-16-at-141949-zwart-wit.jpeg'
  WHEN 'Kees van Miltenburg' THEN 'https://www.fresh-forward.nl/thumbnail/team/77/kees-1.jpg'
  WHEN 'Stanley van Kuilenburg' THEN 'https://www.fresh-forward.nl/thumbnail/team/861/stanley-3.jpg'
  WHEN 'Jack de Raadt' THEN 'https://www.fresh-forward.nl/thumbnail/team/78/jack-1.jpg'
  WHEN 'Jan van Loenen' THEN 'https://www.fresh-forward.nl/thumbnail/team/1008/whatsapp-image-2023-05-16-at-141946-1-zwart-wit.jpeg'
  WHEN 'Barry de Vries' THEN 'https://www.fresh-forward.nl/thumbnail/team/1053/barry-4-zwart-wit.jpeg'
  WHEN 'Janneke Goets' THEN 'https://www.fresh-forward.nl/thumbnail/team/857/janneke-2.jpg'
  ELSE foto_key END
WHERE naam IN ('Teunis Sikma','Bert Meulenbroek','Joanna Pabiniak','Stephan Geerlings','Peter-Jan van Ingen','Ingrid van der Bogt','Robert Hooftman','Carina van der Lippe','Lucie Bartels','Ilja Berendsen-van der Woude','Nick Howard','Evert Walraven','Anke Fischer','Thijs van Dijk','Rob d''Hont','Gerwin Peters','Yanning Wang','Johan Willemsen','Tim Koorevaar','Marina Gomez-Caro Gonzalez','Rian Zegers-Peters','Ruud Venner','Jiahui Lin','Saskia van Vulpen','Wendelien de Graaf','Imke van Asseldonk-van den Hoven','Kees van Miltenburg','Stanley van Kuilenburg','Jack de Raadt','Jan van Loenen','Barry de Vries','Janneke Goets');
