-- Volledig schema (gespiegeld van productie fresh-forward-db, 9 juni 2026).
-- Toepassen op de TEST-database:
--   npx wrangler d1 execute fresh-forward-db-test --remote --file=migratie/schema-test.sql
CREATE TABLE IF NOT EXISTS afdelingen (id TEXT PRIMARY KEY, naam TEXT);
CREATE TABLE IF NOT EXISTS agenda_events (id TEXT PRIMARY KEY, title TEXT NOT NULL, description TEXT, location TEXT, category TEXT NOT NULL, start_at INTEGER NOT NULL, end_at INTEGER NOT NULL, all_day INTEGER NOT NULL DEFAULT 0, source TEXT NOT NULL DEFAULT 'manual', external_id TEXT, created_by TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS app_settings (tenant_id TEXT NOT NULL DEFAULT 'default', key TEXT NOT NULL, value TEXT, updated_at INTEGER, PRIMARY KEY (tenant_id, key));
CREATE TABLE IF NOT EXISTS ask_log (id TEXT PRIMARY KEY, user_ref TEXT, question TEXT NOT NULL, answered INTEGER NOT NULL, source_ids TEXT, created_at INTEGER NOT NULL DEFAULT (unixepoch()));
CREATE TABLE IF NOT EXISTS audit_log (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'default', actor TEXT, action TEXT NOT NULL, entity TEXT, entity_id TEXT, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS bezoekmeldingen (id TEXT PRIMARY KEY, bezoeker TEXT, bedrijf TEXT, email TEXT, verwacht_op TEXT, reden TEXT, status TEXT, ingecheckt_om TEXT, vertrokken_om TEXT, opmerkingen TEXT, host_id TEXT, aangemeld_door_id TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS bugmeldingen (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'default', melder_id TEXT, melder_naam TEXT, titel TEXT NOT NULL, omschrijving TEXT, screenshot_key TEXT, status TEXT NOT NULL DEFAULT 'open', created_at INTEGER NOT NULL, resolved_at INTEGER);
CREATE TABLE IF NOT EXISTS course_chapters (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'default', course_id TEXT NOT NULL, title TEXT NOT NULL, body TEXT, sort INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS course_progress (tenant_id TEXT NOT NULL DEFAULT 'default', player_id TEXT NOT NULL, course_id TEXT NOT NULL, chapter_id TEXT NOT NULL, done INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL, PRIMARY KEY (tenant_id, player_id, chapter_id));
CREATE TABLE IF NOT EXISTS courses (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'default', title TEXT NOT NULL, description TEXT, sort INTEGER NOT NULL DEFAULT 0, published INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS documenten (id TEXT PRIMARY KEY, titel TEXT, omschrijving TEXT, externe_link TEXT, categorie TEXT, bestandssleutel TEXT, bestandsnaam TEXT, afbeelding_key TEXT, eigenaar_id TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS emoji_reacties (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'default', target_type TEXT NOT NULL, target_id TEXT NOT NULL, emoji TEXT NOT NULL, auteur_id TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(tenant_id, target_type, target_id, emoji, auteur_id));
CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT, ts TEXT, type TEXT, ref TEXT, detail TEXT, actor TEXT);
CREATE TABLE IF NOT EXISTS kb_docs (id TEXT PRIMARY KEY, category TEXT NOT NULL, variety TEXT, title TEXT NOT NULL, body TEXT NOT NULL, url TEXT, audience TEXT NOT NULL DEFAULT 'internal' CHECK (audience IN ('public','grower','internal')), updated_at INTEGER NOT NULL DEFAULT (unixepoch()));
CREATE TABLE IF NOT EXISTS kb_chunks (id TEXT PRIMARY KEY, doc_id TEXT NOT NULL REFERENCES kb_docs(id) ON DELETE CASCADE, chunk_ix INTEGER NOT NULL, text TEXT NOT NULL, created_at INTEGER NOT NULL DEFAULT (unixepoch()));
CREATE TABLE IF NOT EXISTS klantdocumenten (id TEXT PRIMARY KEY, titel TEXT, omschrijving TEXT, externe_link TEXT, bestandssleutel TEXT, bestandsnaam TEXT, categorie TEXT, gepubliceerd INTEGER DEFAULT 0, afbeelding_key TEXT);
CREATE TABLE IF NOT EXISTS klanten (id TEXT PRIMARY KEY, naam TEXT, email TEXT, bedrijf TEXT, actief INTEGER DEFAULT 1, laatste_login TEXT, notitie TEXT, taal TEXT);
CREATE TABLE IF NOT EXISTS matches (id TEXT PRIMARY KEY, game_type TEXT NOT NULL, player_a TEXT NOT NULL, player_b TEXT NOT NULL, winner TEXT NOT NULL, score_a INTEGER, score_b INTEGER, elo_a_before INTEGER, elo_a_after INTEGER, elo_b_before INTEGER, elo_b_after INTEGER, tournament_id TEXT, played_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS medewerkers (id TEXT PRIMARY KEY, naam TEXT, email TEXT, rol TEXT, afdeling TEXT, actief INTEGER DEFAULT 1, foto_key TEXT, telefoon TEXT, verjaardag TEXT, nieuws_gezien TEXT, functie TEXT, created_at TEXT, nickname TEXT, intro_tune TEXT, roles TEXT NOT NULL DEFAULT '', verjaardag_zichtbaar INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS meldingen (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'default', type TEXT NOT NULL, titel TEXT NOT NULL, omschrijving TEXT, locatie TEXT, gemeld_door TEXT, gemeld_naam TEXT, status TEXT NOT NULL DEFAULT 'open', created_at INTEGER NOT NULL, resolved_at INTEGER);
CREATE TABLE IF NOT EXISTS nieuws (id TEXT PRIMARY KEY, titel TEXT, inhoud TEXT, categorie TEXT, publicatiedatum TEXT, status TEXT, zichtbaarheid TEXT, uitgelicht INTEGER DEFAULT 0, afbeelding_key TEXT, auteur_id TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS nieuws_reacties (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'default', nieuws_id TEXT NOT NULL, auteur_id TEXT, reactie TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS noodmeldingen (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'default', melder_id TEXT, melder_naam TEXT, locatie TEXT, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS player_game_prefs (player_id TEXT NOT NULL, game_type TEXT NOT NULL, voice_calls INTEGER NOT NULL DEFAULT 1, PRIMARY KEY (player_id, game_type));
CREATE TABLE IF NOT EXISTS poll_stemmen (id TEXT PRIMARY KEY, poll_id TEXT NOT NULL, optie INTEGER NOT NULL, stemmer_id TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS polls (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'default', vraag TEXT NOT NULL, opties TEXT NOT NULL, multi INTEGER NOT NULL DEFAULT 0, maker_id TEXT, maker_naam TEXT, status TEXT NOT NULL DEFAULT 'open', created_at INTEGER NOT NULL, closes_at INTEGER);
CREATE TABLE IF NOT EXISTS posts (id TEXT PRIMARY KEY, bericht TEXT, auteur_id TEXT, created_at TEXT, afbeelding_key TEXT, ontvanger_id TEXT);
CREATE TABLE IF NOT EXISTS pushabonnementen (id TEXT PRIMARY KEY, endpoint TEXT UNIQUE, email TEXT, p256dh TEXT, auth TEXT, laatst_gebruikt TEXT);
CREATE TABLE IF NOT EXISTS rassen (id TEXT PRIMARY KEY, naam TEXT, gewas TEXT, omschrijving TEXT, smaak TEXT, kleur TEXT, seizoen TEXT, afbeelding_key TEXT, volgorde INTEGER, gepubliceerd INTEGER DEFAULT 0, bestandssleutel TEXT, bestandsnaam TEXT);
CREATE TABLE IF NOT EXISTS ratings (player_id TEXT NOT NULL, game_type TEXT NOT NULL, elo INTEGER NOT NULL DEFAULT 1000, wins INTEGER NOT NULL DEFAULT 0, losses INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (player_id, game_type));
CREATE TABLE IF NOT EXISTS reacties (id TEXT PRIMARY KEY, reactie TEXT, post_id TEXT REFERENCES posts(id) ON DELETE CASCADE, auteur_id TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS snack_ledger (id TEXT PRIMARY KEY, player_id TEXT NOT NULL, amount_cents INTEGER NOT NULL, kind TEXT NOT NULL, description TEXT, created_by TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS snack_menu (id TEXT PRIMARY KEY, name TEXT NOT NULL, price_cents INTEGER NOT NULL, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS snoei_pluk (id TEXT PRIMARY KEY, titel TEXT, type TEXT, inhoud TEXT, ras_id TEXT, periode TEXT, volgorde INTEGER, gepubliceerd INTEGER DEFAULT 0, afbeelding_key TEXT, bestandssleutel TEXT, bestandsnaam TEXT);
CREATE TABLE IF NOT EXISTS teeltadvies (id TEXT PRIMARY KEY, titel TEXT, inhoud TEXT, ras_id TEXT, categorie TEXT, volgorde INTEGER, gepubliceerd INTEGER DEFAULT 0, afbeelding_key TEXT, bestandssleutel TEXT, bestandsnaam TEXT);
CREATE TABLE IF NOT EXISTS tournament_players (tournament_id TEXT NOT NULL, player_id TEXT NOT NULL, PRIMARY KEY (tournament_id, player_id));
CREATE TABLE IF NOT EXISTS tournaments (id TEXT PRIMARY KEY, game_type TEXT NOT NULL, name TEXT NOT NULL, format TEXT NOT NULL, status TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS user_module_seen (user_id TEXT NOT NULL, module_key TEXT NOT NULL, last_seen_at INTEGER NOT NULL, PRIMARY KEY (user_id, module_key));
CREATE TABLE IF NOT EXISTS verlof (id TEXT PRIMARY KEY, external_id TEXT, employee_email TEXT, employee_name TEXT NOT NULL, type TEXT, start_at INTEGER NOT NULL, end_at INTEGER NOT NULL, status TEXT, source TEXT NOT NULL DEFAULT 'buddee', synced_at INTEGER, afdeling TEXT);
CREATE TABLE IF NOT EXISTS vertaal_cache (id TEXT PRIMARY KEY, lang TEXT NOT NULL, vertaald TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_agenda_range ON agenda_events (start_at, end_at);
CREATE INDEX IF NOT EXISTS idx_asklog_time ON ask_log(created_at);
CREATE INDEX IF NOT EXISTS idx_audit ON audit_log (tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_bezoek_created ON bezoekmeldingen(created_at);
CREATE INDEX IF NOT EXISTS idx_bezoek_verwacht ON bezoekmeldingen(verwacht_op);
CREATE INDEX IF NOT EXISTS idx_bug_status ON bugmeldingen (tenant_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_chapters_course ON course_chapters (tenant_id, course_id, sort);
CREATE INDEX IF NOT EXISTS idx_chunks_doc ON kb_chunks(doc_id);
CREATE INDEX IF NOT EXISTS idx_emoji_target ON emoji_reacties(tenant_id, target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_events_ts ON events(ts);
CREATE INDEX IF NOT EXISTS idx_klantdoc_pub ON klantdocumenten(gepubliceerd);
CREATE INDEX IF NOT EXISTS idx_klanten_email ON klanten(email);
CREATE INDEX IF NOT EXISTS idx_matches_game ON matches (game_type, played_at);
CREATE INDEX IF NOT EXISTS idx_medewerkers_email ON medewerkers(email);
CREATE INDEX IF NOT EXISTS idx_medewerkers_naam ON medewerkers(naam);
CREATE INDEX IF NOT EXISTS idx_meldingen_status ON meldingen (tenant_id, status, type);
CREATE INDEX IF NOT EXISTS idx_nieuws_pub ON nieuws(publicatiedatum);
CREATE INDEX IF NOT EXISTS idx_nieuws_reacties_nieuws ON nieuws_reacties(tenant_id, nieuws_id);
CREATE INDEX IF NOT EXISTS idx_nieuws_status ON nieuws(status);
CREATE INDEX IF NOT EXISTS idx_nood_tijd ON noodmeldingen (tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_poll_stemmen_poll ON poll_stemmen(poll_id);
CREATE INDEX IF NOT EXISTS idx_posts_created ON posts(created_at);
CREATE INDEX IF NOT EXISTS idx_rassen_pub ON rassen(gepubliceerd, volgorde);
CREATE INDEX IF NOT EXISTS idx_reacties_post ON reacties(post_id);
CREATE INDEX IF NOT EXISTS idx_snack_player ON snack_ledger (player_id);
CREATE INDEX IF NOT EXISTS idx_snoei_pub ON snoei_pluk(gepubliceerd, volgorde);
CREATE INDEX IF NOT EXISTS idx_teelt_pub ON teeltadvies(gepubliceerd, volgorde);
CREATE INDEX IF NOT EXISTS idx_verlof_range ON verlof(start_at, end_at);
CREATE INDEX IF NOT EXISTS idx_verlof_src ON verlof(source);
